credentials:
  usernames: inv247
    admin:
      email: inv247
      name: inv247
      password: inv247 # To be replaced with hashed password

cookie:
  expiry_days: 30
  key: admin_signature_key # Must be string
  name: admin_cookie
preauthorized:
  emails:
  - hania502@hotmail.com
